spring:
  cloud:
    gateway:
      routes:
        - id: ingress-graphql-bff
          uri: http://localhost:8080
          predicates:
            - Method=POST
server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always